### ISSUE TITLE
destroyDialog() referencing `this` instead of `#timeout-dialog`

### ISSUE THREAD

**Issue by rawtaz** [digitick/yii-timeout-dialog#1]
Hi,

I'm not entirely sure that what I'm going to report here is accurate, because I have had this extension working at one point in time a month or so ago (so it totally beats me why I haven't found this at that point in time), but from what and all I can tell now there's a problem in the `destroyDialog()` function of the JS code.

In short, the dialog loads and displays just fine, but when I click e.g. the keep alive button, I get this error and there is no action being taken by the buttons (both in FF19 and Chrome 24.0.1312.57):

```
Error: cannot call methods on dialog prior to initialization; attempted to call method 'close'
```

Having spent some time debugging this my conclusion is that it happens in/due to the `destroyDialog()` function. In it there's a `$(this).dialog("close")` call, but from what I can tell, `this` does not refer to the DOM element that represents the dialog, it refers to the plugin/jQuery object which is not something that one should call `dialog('close')` on.

So, my question is, shouldn't this code be `$("#timeout-dialog").dialog("close")` instead?

For the record, if I change that code to what I suggest, the buttons work correctly and I don't get the error.

**Comment by ianare** [comment]
You were right. Consider a pull request next time ;-)

**Comment by rawtaz** [comment]
I wasn't sure I was right ;_;

Thank you for fixing :)
